project_name: thinkport
report_sizes: true
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - arm
      - arm64
    ldflags: -s -w
    hooks:
      pre:
        - go generate ./...
      post:
        - echo "Build completed!"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    builds_info:
      group: root
      owner: root
      mode: 0644

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  mode: append
  github:
    owner: vergissberlin
    name: thinkport
  header: |
    ## Thinkport CLI release
    _{{ .Date }}_

    🚀 Welcome to this new release!

    Run `brew update && brew upgrade thinkport` to get the latest version.
    With `thinkport -v` you can check the version you are running.

  # Footer for the release body.
  #
  # Templates: allowed
  footer: |

    ---
    *[Thinkport Gmbh](https://thinkport.digital)* | Those were the changes on [{{ .Tag }}](https://github.com/vergissberlin/thinkport/releases/tag/{{ .Tag }})!

brews:
  - name: thinkport
    homepage: 'https://github.com/vergissberlin/thinkport'
    description: 'This cli tool provides a set of commands related to Thinkport. This is a technical experiement and not intended for production use.'
    caveats: 'It uses a http client to collect the data. Internet connection is required.'
    license: 'MIT'
    commit_author:
      name: vergissberlin
      email: vergissberlin@googlemail.com
    goarm: '7'
    directory: Formula
    test: |
      system "#{bin}/thinkport", "--version"
    repository:
      name: homebrew-tap
      owner: vergissberlin
      branch: main
      token: '{{ .Env.TAP_GITHUB_TOKEN }}'
    url_template: "https://github.com/vergissberlin/thinkport/releases/download/{{ .Version }}/thinkport_{{ .Os }}_{{ .Arch }}.tar.gz"
    install: |
      bin.install "thinkport"

announce:
  webhook:
    enabled: true
    skip_tls_verify: true
    message_template: '{ "message": "🚀 *New release {{.Tag}}* of {{ 
    .ProjectName }} is out!\nCheck it out at {{ .ReleaseURL }}.\nYou can 
    install with `brew install vergissberlin/tap/thinkport` and upgrade 
    with `brew update && brew upgrade thinkport`. "}'
    endpoint_url: 'https://iot.andrelademann.de/releases/thinkport-cli'

  slack:
    enabled: true
    channel: "#tp-other"
    username: "ThinkBot"
    blocks:
      - type: section
        text:
          type: mrkdwn
          text: "🚀 *Release {{.Tag}} of Tinkport CLI is out!*"

      - type: section
        text:
          type: mrkdwn
          text: "Install it with `brew install vergissberlin/tap/thinkport`\nor upgrade with `brew update && brew upgrade thinkport`."

      - type: section
        text:
          type: mrkdwn
          text: "Take a look at the <{{ .ReleaseURL }}|release notes> to see what's new."
        accessory:
          type: button
          text:
            type: plain_text
            text: "📄 Release notes {{.Tag}}"
            emoji: true
          value: "release_notes"
          url: "{{ .ReleaseURL }}"
          action_id: "button-action"