# GitHub Action to test go code
on: [push]

name: Test

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Test
            uses: ./
            with:
            args: go test -v ./...
            
